"""added city

Revision ID: e86f61e9e568
Revises: d72ec08b99a5
Create Date: 2025-08-07 21:48:36.247825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e86f61e9e568"
down_revision: Union[str, None] = "d72ec08b99a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_locations",
        sa.Column("city", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_locations", "city")
    # ### end Alembic commands ###
