"""Added email confirmation

Revision ID: c093696fe9eb
Revises: b8c0b5d87f9e
Create Date: 2025-06-30 20:33:25.662296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c093696fe9eb"
down_revision: Union[str, None] = "b8c0b5d87f9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("email_is_confirmed", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email_is_confirmed")
    # ### end Alembic commands ###
