"""location

Revision ID: 2acc94137013
Revises: 2b852487fa4a
Create Date: 2025-08-07 01:54:44.935574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2acc94137013"
down_revision: Union[str, None] = "2b852487fa4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usersession")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usersession",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "refresh_token", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "exp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "iat", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "is_blacklisted", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("usersession_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("usersession_pkey")),
    )
    # ### end Alembic commands ###
