
services:
  db:
    image: postgis/postgis:13-3.3 
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pet_db      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  # Раскомментируйте, если нужен Redis
  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:  


