services:
  db:
    image: postgis/postgis:13-3.3 
    restart: always                 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pet_db      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    networks:
      - pet-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - pet-network

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    # environment:
    #   - REDIS_PASSWORD=admin
    volumes:
      - redis_data:/data
    networks:
      - pet-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    depends_on: 
      - redis
    restart: always
    volumes:
      - redis_insight_data:/data
    ports: 
      - "5540:5540"
    networks: 
      - pet-network

networks:
  pet-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  redis_insight_data: